### ISSUE TITLE
README and `lib.rs` rustdoc are duplicate

### ISSUE THREAD

**Issue by tcharding** [Kixunil/lgio#2]
The docs in the `README` and `lib.rs` are the same, is this intentional?

**Comment by Kixunil** [comment]
Yes, it is.

**Comment by tcharding** [comment]
Is one generated from the other or created manually?

**Comment by Kixunil** [comment]
Manual copy-paste. Yeah, it's not great but the feature that enables including the readme requires new compiler (cfg doesn't work because it's a change to Rust code parser).
